// Reads .env and generates extension config files with actual values
// Run: node build.js

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const extDir = path.join(__dirname, 'extension');

// Parse .env file
const envContent = fs.readFileSync(envPath, 'utf-8');
const env = {};
for (const line of envContent.split('\n')) {
  const match = line.match(/^\s*([A-Z_]+)\s*=\s*"?([^"]*)"?\s*$/);
  if (match) env[match[1]] = match[2];
}

// Validate required variables
const required = ['AZURE_CLAUDE_API_KEY', 'AZURE_CLAUDE_ENDPOINT', 'AZURE_CLAUDE_MODEL', 'AZURE_CLAUDE_API_VERSION', 'SAP_HOSTNAME', 'SAP_CLIENT', 'SAP_ODATA_PATH'];
const missing = required.filter(k => !env[k]);
if (missing.length > 0) {
  console.error('Missing required .env variables:', missing.join(', '));
  console.error('See .env.example for the full list.');
  process.exit(1);
}

const hostname = env.SAP_HOSTNAME;
const azureHost = env.AZURE_CLAUDE_ENDPOINT.match(/https:\/\/[^/]+/)[0];

// --- config.js (API + SAP connection settings) ---
const config = `// AUTO-GENERATED by build.js - DO NOT COMMIT
const CONFIG = {
  apiKey: '${env.AZURE_CLAUDE_API_KEY}',
  endpoint: '${env.AZURE_CLAUDE_ENDPOINT}',
  model: '${env.AZURE_CLAUDE_MODEL}',
  apiVersion: '${env.AZURE_CLAUDE_API_VERSION}',
  sapHostname: '${hostname}',
  sapClient: '${env.SAP_CLIENT}',
  sapODataPath: '${env.SAP_ODATA_PATH}',
};
`;
fs.writeFileSync(path.join(extDir, 'config.js'), config);

// --- manifest.json (dynamic hostname) ---
const manifest = {
  manifest_version: 3,
  name: 'SAP Hours Agent',
  version: '2.0.0',
  description: 'AI-powered time entry assistant for SAP Fiori',
  permissions: ['activeTab', 'tabs', 'storage'],
  host_permissions: [
    `https://${hostname}/*`,
    `${azureHost}/*`,
  ],
  background: { service_worker: 'background.js' },
  content_scripts: [{
    matches: [`https://${hostname}/*`],
    js: ['config.js', 'content.js'],
    run_at: 'document_idle',
  }],
  action: { default_title: 'SAP Hours Agent' },
  web_accessible_resources: [{
    resources: ['sidepanel.html', 'sidepanel.js', 'config.js'],
    matches: [`https://${hostname}/*`],
  }],
  icons: { '48': 'icons/icon48.png', '128': 'icons/icon128.png' },
};
fs.writeFileSync(path.join(extDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

console.log('Generated:');
console.log('  extension/config.js');
console.log('  extension/manifest.json');
console.log(`  SAP host: ${hostname}`);
console.log('  User info will be auto-discovered from SAP at runtime.');
