// Reads .env and generates extension config files with actual values
// Run: node build.js

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const extDir = path.join(__dirname, 'extension');

// Parse .env file
const envContent = fs.readFileSync(envPath, 'utf-8');
const env = {};
for (const line of envContent.split('\n')) {
  const match = line.match(/^\s*([A-Z_]+)\s*=\s*"?([^"]*)"?\s*$/);
  if (match) env[match[1]] = match[2];
}

// --- config.js (API settings) ---
const config = `// AUTO-GENERATED by build.js - DO NOT COMMIT
const CONFIG = {
  apiKey: '${env.AZURE_CLAUDE_API_KEY}',
  endpoint: '${env.AZURE_CLAUDE_ENDPOINT}',
  model: '${env.AZURE_CLAUDE_MODEL || 'claude-sonnet-4-5'}',
  apiVersion: '${env.AZURE_CLAUDE_API_VERSION || '2023-06-01'}',
};
`;
fs.writeFileSync(path.join(extDir, 'config.js'), config);

// --- user-config.js (SAP + user settings) ---
const hostname = env.SAP_HOSTNAME || 'your-sap-host.example.com';
const userConfig = `// AUTO-GENERATED by build.js - DO NOT COMMIT
const USER_CONFIG = {
  sapHostname: '${hostname}',
  sapClient: '${env.SAP_CLIENT || '100'}',
  sapODataPath: '${env.SAP_ODATA_PATH || '/sap/opu/odata/sap/ZHR_TIME_ENTRY_SRV'}',
  persNumber: '${env.SAP_PERS_NUMBER || ''}',
  userName: '${env.SAP_USER_NAME || ''}',
  displayName: '${env.SAP_USER_DISPLAY_NAME || ''}',
  userTitle: '${env.SAP_USER_TITLE || ''}',
  company: '${env.SAP_COMPANY || ''}',
  costCenter: '${env.SAP_COST_CENTER || ''}',
  defaultRole: '${env.SAP_DEFAULT_ROLE || 'ZADMIN'}',
};
`;
fs.writeFileSync(path.join(extDir, 'user-config.js'), userConfig);

// --- manifest.json (dynamic hostname) ---
const azureHost = (env.AZURE_CLAUDE_ENDPOINT || '').match(/https:\/\/[^/]+/)?.[0] || 'https://your-azure-endpoint.example.com';
const manifest = {
  manifest_version: 3,
  name: 'SAP Hours Agent',
  version: '1.2.0',
  description: 'AI-powered time entry assistant for SAP Fiori',
  permissions: ['activeTab', 'tabs', 'storage'],
  host_permissions: [
    `https://${hostname}/*`,
    `${azureHost}/*`,
  ],
  background: { service_worker: 'background.js' },
  content_scripts: [{
    matches: [`https://${hostname}/*`],
    js: ['user-config.js', 'content.js'],
    run_at: 'document_idle',
  }],
  action: { default_title: 'SAP Hours Agent' },
  web_accessible_resources: [{
    resources: ['sidepanel.html', 'sidepanel.js', 'config.js', 'user-config.js'],
    matches: [`https://${hostname}/*`],
  }],
  icons: { '48': 'icons/icon48.png', '128': 'icons/icon128.png' },
};
fs.writeFileSync(path.join(extDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

console.log('Generated:');
console.log('  extension/config.js');
console.log('  extension/user-config.js');
console.log('  extension/manifest.json');
console.log(`  SAP host: ${hostname}`);
console.log(`  User: ${env.SAP_USER_DISPLAY_NAME || '(not set)'}`);
